### ISSUE TITLE
unexpected keyword argument 'thread_name_prefix'

### ISSUE THREAD

**Issue by ghost** [SylvanasSun/python-common-cache#3]
In Ubuntu 18 using Python 3.5.2, doing:
`from common_cache import Cache
import logging
cache = Cache(log_level=logging.WARNING)`

the result is:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/common_cache/__init__.py", line 277, in __init__
    self.thread_pool = thread_pool_init_func()
  File "/usr/local/lib/python3.5/dist-packages/common_cache/__init__.py", line 101, in _init_thread_pool
    return ThreadPoolExecutor(max_workers=max_workers, thread_name_prefix=thread_name_prefix)
TypeError: __init__() got an unexpected keyword argument 'thread_name_prefix'`

python -m pip show python-common-cache
Name: python-common-cache
Version: 0.1

Any idea? Thx

**Comment by ghost** [comment]
Once updated to python 3.7 the problem no longer occurs
Thx
